const actionTypes = {
  // APP
  ACTION_UPDATE_APP: 'app/ACTION_UPDATE_APP',
  ACTION_SET_LOADING: 'app/ACTION_SET_LOADING',
  ACTION_INIT_APP: 'app/ACTION_INIT_APP',
  ACTION_REFRESH_APP: 'app/ACTION_REFRESH_APP',
  // AUTH
  ACTION_UPDATE_AUTH: 'auth/ACTION_UPDATE_AUTH',
  ACTION_INIT_AUTH: 'auth/ACTION_INIT_AUTH',
  ACTION_LOGIN: 'auth/ACTION_LOGIN',
  ACTION_LOGOUT: 'auth/ACTION_LOGOUT',
};

export default actionTypes;
